config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { 
    :omniauth_callbacks => "users/omniauth_callbacks",
    registrations: 'users/registrations'

     }

  resources :articles
  resources :documents
  resources :definitions
  resources :events
  resources :contacts
  resources :todo_lists
  resources :todos, only:[:create,:update,:destroy]
  
  resources :tags, only: [:index] do
    collection do 
      get "suggest(/:query)", as: :suggest, action: :suggest
    end
  end

  get  '/login', :to => 'sessions#new', :as => :login
  get  '/onedrive', :to => 'sessions#onedrive_login', :as => :onedrive
  get '/auth/onedrive/callback', to: 'sessions#onedrive_callback'
  get '/auth/failure', :to => 'sessions#failure'
  get '/auth/test', :to => 'sessions#test'
  post '/auth/test', :to => 'sessions#test'
  get '/post', :to => 'sessions#post'

  get :items, to: 'items#index'

  
  root 'pages#home'
end

app/models/event.rb
class Event < Item

  validates :start, presence: true

  def full_day
    self.end.blank? or self.start == self.start.midnight()
  end

  def full_day=(val)
  end

  def description
    return self.pre unless pre.blank?
    return self.content
  end

  def link=value
    self.infos.where(ref: 'link').first_or_create.tap do  |info|
      info.update content: value,
        title: 'link'
    end
  end
  
  def calendar_id=value
    self.infos.where(ref: 'calendar_id').first_or_create.tap do  |info|
      info.update content: value,
        title: 'calendar_id'
    end
  end

end

app/controllers/events_controller.rb
class EventsController < ItemsController
  require 'apis'

  before_action :authenticate_user!

  def index
    @items = current_user.items.all.where.not('start' => nil)
    @items = @items.where('start >= ?',params[:start]) unless params[:start].blank?
    @items = @items.where('start <= ?',params[:end]) unless params[:end].blank?
  end


  def create
    super do |event|

      api = Apis::GoogleCalendar.new current_user.tokens.refresheable.provider('google_oauth2').last
      api.create_event(event)

    end
  end


  def update
    super do |event|

      api = Apis::GoogleCalendar.new current_user.tokens.refresheable.provider('google_oauth2').last
      api.update_event(event)

    end
  end

  protected

  def item_params
    params.require(:event).permit(:title, :pre, :content, :start, :end, related_items_attributes: [:id, :title, :related_item_id, :position, :_destroy], infos_attributes: [:id, :title, :content, :ref, :_destroy])
  end

  def items_scope
    current_user.items.events
  end

end

app/views/events/_form.html.haml
= simple_form_for @item, :html => { :class => '' } do |f|

  .panel.panel-default
    .panel-heading
      Attributes
    .panel-body
      .row
        .col-xs-4
          = f.input :title
          = f.error_span :title
        .col-xs-8
          = f.input :tags, input_html:{class: 'tags_select',  multiple: true}, collection: @item.tags.map(&:title), selected: @item.tags.map(&:title)
      .row
        .col-xs-6
          = f.input :start, :as => :datetime_picker
          = f.error_span :start
        .col-xs-6
          = f.input :end, :as => :datetime_picker
          = f.error_span :end
      = f.input :pre
      = f.error_span :pre

  = render 'shared/info_form', f: f
  = render 'shared/item_form', f: f

  = f.input :content, input_html:{class: 'markdown_editor'}
  = f.error_span :content



  = f.button :submit, :class => 'btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), events_path, :class => 'btn btn-default'

app/views/events/edit.html.haml
- model_class = Event
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/events/index.html.haml
- model_class = Event
.page-header
  = render "shared/link_index_top", model_class: model_class
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize

#calendar

= link_to t('.new', :default => t("helpers.links.new")), new_event_path, :class => 'btn btn-primary'

app/views/events/new.html.haml
- model_class = Event
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/events/show.html.haml
-content_for :meta do
  =render 'shared/tag_show', item: @item

- model_class = Event
.page-header
  = render "shared/link_show_top", item: @item
  %h1=@item.title

= render "shared/info_show", item: @item

= render "shared/pre_show", item: @item
    
= render "shared/content_show", item: @item

= render "shared/related_show", item: @item

= render "shared/link_show_bottom", item: @item