config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { 
    :omniauth_callbacks => "users/omniauth_callbacks",
    registrations: 'users/registrations'

     }

  resources :articles
  resources :documents
  resources :definitions
  resources :events
  resources :contacts
  resources :todo_lists
  resources :todos, only:[:create,:update,:destroy]
  
  resources :tags, only: [:index] do
    collection do 
      get "suggest(/:query)", as: :suggest, action: :suggest
    end
  end

  get  '/login', :to => 'sessions#new', :as => :login
  get  '/onedrive', :to => 'sessions#onedrive_login', :as => :onedrive
  get '/auth/onedrive/callback', to: 'sessions#onedrive_callback'
  get '/auth/failure', :to => 'sessions#failure'
  get '/auth/test', :to => 'sessions#test'
  post '/auth/test', :to => 'sessions#test'
  get '/post', :to => 'sessions#post'

  get :items, to: 'items#index'

  
  root 'pages#home'
end

app/models/item.rb
class Item < ActiveRecord::Base

  belongs_to :user
  has_and_belongs_to_many :tags
  has_many :infos, dependent: :destroy
  has_many :todos, dependent: :destroy
  has_many :related_items, dependent: :destroy
  has_many :items, :through => :related_items
  has_many :inverse_related_items, :class_name => "RelatedItem", :foreign_key => "related_item_id", dependent: :destroy
  has_many :inverse_items, :through => :inverse_related_items, :source => :item

  accepts_nested_attributes_for :tags
  accepts_nested_attributes_for :todos
  accepts_nested_attributes_for :infos
  accepts_nested_attributes_for :related_items, reject_if: :all_blank, allow_destroy: true

  scope :articles, ->{where(type: "Article")}
  scope :documents, ->{where(type: "Document")}
  scope :contacts, ->{where(type: "Contact")}
  scope :definitions, ->{where(type: "Definition")}
  scope :events, ->{where(type: "Event")}
  scope :todo_lists, ->{where(type: "TodoList")}

  def tag_string
    self.tags.map(&:title).join(' ')
  end

  def tag_string=(string)
    t = Tag.create_from_string(string)
    self.tags = t.uniq
  end

end


class RelatedItem < ActiveRecord::Base
  belongs_to :item
  belongs_to :related_item, :class_name => "Item"
  default_scope {order(position: 'asc')}
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :authenticate_user!, :get_class

  def index
    @q = items_scope.order(created_at: 'desc').ransack(params[:q])
    @items = @q.result(distinct: true).page(params[:page])

  end

  def new
    @item = @klass.new
  end

  def create
    @item = @klass.new(params_with_tag)
    # return render json: @item.tags
    @item.user_id = current_user.id
    flash[:info] = "'#{@item.title}' created" if @item.save

    yield @item if block_given?

    respond_with @item, location: url_for(@klass)
  end

  def edit
    @item = items_scope.find(params[:id])
  end

  def update
    # return render json: tags_params
    @item = items_scope.find(params[:id])
    flash[:info] = "'#{@item.title}' updated" if @item.update(params_with_tag)

    yield @item if block_given?

    respond_with @item, location: url_for(@klass)
  end

  def show
    @item = items_scope.find(params[:id])
  end

  def destroy
    item = items_scope.find(params[:id])
    item.destroy()
    flash[:info] = "'#{item.title}' deleted"
    respond_with item, location: url_for(@klass)
  end
 

  protected

  def item_params
    params.require(@sym).permit(:title, :pre, :content, related_items_attributes: [:id, :title, :related_item_id, :position, :_destroy], infos_attributes: [:id, :title, :content, :ref, :_destroy])
  end

  def tags_params
    params.require(@sym).permit(tags:[])
  end

  def params_with_tag
    prms = item_params.as_json
    prms[:tag_string] = tags_params[:tags].compact.uniq.join(' ') unless tags_params[:tags].blank?
    prms
  end

  def items_scope
    current_user.items
  end

  def get_class
    @sym = controller_name.singularize.to_sym
    @klass = controller_name.singularize.camelize.constantize
  end



end

app/views/items/_item_td.html.haml
%tr
  %td= link_to item.title, item
  %td= truncate item.pre, length: 200
  %td
    -item.tags.each do |tag|
      =link_to tag.title, [Item, q: {tags_title_eq: tag.title}] 


  %td=l item.created_at, format: :short
  %td
    = link_to t('.edit', :default => t("helpers.links.edit")), [:edit, item], :class => 'btn btn-default btn-xs'
    = link_to t('.destroy', :default => t("helpers.links.destroy")), item, :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

app/views/items/index.html.haml
- model_class = Item
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize

=search_form_for @q, url: items_path   do |f|
  .row
    .form-group.col-md-3
      =f.search_field :tags_title_eq, class:"form-control"
    .form-group.col-md-3
      =submit_tag 'Search', class:'btn btn-default'
  
= render 'shared/index_table'

= will_paginate @items, renderer: BootstrapPagination::Rails, class:'pull-right'