config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { 
    :omniauth_callbacks => "users/omniauth_callbacks",
    registrations: 'users/registrations'

     }

  resources :articles
  resources :documents
  resources :definitions
  resources :events
  resources :contacts
  resources :todo_lists
  resources :todos, only:[:create,:update,:destroy]
  
  resources :tags, only: [:index] do
    collection do 
      get "suggest(/:query)", as: :suggest, action: :suggest
    end
  end

  get  '/login', :to => 'sessions#new', :as => :login
  get  '/onedrive', :to => 'sessions#onedrive_login', :as => :onedrive
  get '/auth/onedrive/callback', to: 'sessions#onedrive_callback'
  get '/auth/failure', :to => 'sessions#failure'
  get '/auth/test', :to => 'sessions#test'
  post '/auth/test', :to => 'sessions#test'
  get '/post', :to => 'sessions#post'

  get :items, to: 'items#index'

  
  root 'pages#home'
end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Brain"
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application",  'data-turbolinks-track' => true
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"

  %body
    .navbar.navbar-default.navbar-static-top
      .container
        %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand(href="/") Brain
        .navbar-collapse.collapse.navbar-responsive-collapse
          %ul.nav.navbar-nav.pull-right
            -if current_user
              %li= link_to "Articles", articles_path
              %li= link_to "Definitions", definitions_path
              %li= link_to "Events", events_path
              %li= link_to "Contacts", contacts_path
              %li= link_to "Todo", todo_lists_path
              %li= link_to "Docs", documents_path
              %li= link_to('Logout', destroy_user_session_path, :method => :delete) 
              %li
                = link_to edit_user_registration_path do 
                  =image_tag current_user.image, class:'img-circle avatar'
            -else
              %li= link_to "Sign in with Google", user_google_oauth2_omniauth_authorize_path




    .container
      .push-down-60
        .meta.push-down-60
          = yield :meta
        
        = bootstrap_flash
        = yield